---
# include:
#   - compose-static-web-server.yml
#   - compose-traefik.yml

networks:
  proxy:
    driver: overlay
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: ${PROXY_NETWORK_IPV4_CIDR:-10.0.0.0/24}
        - subnet: ${PROXY_NETWORK_IPV6_CIDR:-fd00::/64}
...
