---
services:
  resources-reserve:
    command: ["sleep", "infinity"]
    deploy:
      mode: global
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          cpus: 0.5
          memory: 512M
    extends:
      file: compose.templates.yml
      service: service
    image: alpine:3.22.0
...
