---
x-templates:
  network: &network-template
    driver: overlay
    driver_opts:
      encrypted: "true"

  service: &service-template
    deploy: &service-template-deploy
      endpoint_mode: vip
      labels: &service-template-deploy-labels
        eu.cloudskeleton.service: "true"
        eu.cloudskeleton.service.type: service
      mode: replicated
      placement:
        constraints:
          - node.labels.eu.cloudskeleton.node.type==main-worker
      resources: &service-template-deploy-resources
        limits:
          cpus: "0.5"
          memory: 128M
          pids: 1024
        reservations:
          cpus: "0.5"
          memory: 128M
      restart_policy: &service-template-deploy-restart-policy
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      rollback_config: &service-template-deploy-rollback-config
        delay: 10s
        failure_action: continue
        max_failure_ratio: 0
        monitor: 60s
        order: start-first
        parallelism: 1
      update_config: &service-template-deploy-update-config
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0
        monitor: 60s
        order: start-first
        parallelism: 1
    healthcheck: &service-template-deploy-healthcheck
      interval: 10s
      start_interval: 2s
      start_period: 10s
      timeout: 3s
    init: true
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      - bridge
    stop_grace_period: 30s
    ulimits:
      core: 
        hard: 0
        soft: 0
      nofile:
        hard: 40000
        soft: 20000
      nproc:
        hard: 65535
        soft: 65535

networks:
  bridge:
    <<: *network-template
    ipam:
      config:
        - subnet: ${PROXY_NETWORK_IPV4_CIDR:-10.0.0.0/24}

  isolated:
    # <<: *network-template
    # attachable: false
    # internal: true
    external: true
    name: none

services:
  resources-reserve:
    <<: *service-template
    deploy:
      <<: *service-template-deploy
      mode: global
      placement:
        constraints: []
      resources:
        <<: *service-template-deploy-resources
        limits:
          cpus: ${RESERVE_VCPU:-0.5}
          memory: ${RESERVE_MEMORY:-512M}
        reservations:
          cpus: ${RESERVE_VCPU:-0.5}
          memory: ${RESERVE_MEMORY:-512M}
      rollback_config:
        <<: *service-template-deploy-rollback-config
        order: stop-first
        parallelism: 0
      update_config:
        <<: *service-template-deploy-update-config
        order: stop-first
        parallelism: 0
    image: tianon/sleeping-beauty:latest
    networks:
      - isolated
...
