---
include:
  - compose-static-web-server.yml
  - compose-traefik.yml

name: proxy

networks:
  bridge:
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${PROXY_NETWORK_IPV4_CIDR:-10.0.0.0/24}
        - subnet: ${PROXY_NETWORK_IPV6_CIDR:-fd00::/64}

x-podman:
  in_pod: false
...
