---
services:
  job:
    deploy:
      resources:
        limits:
          memory: 128M
    entrypoint: bash -c
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    mem_swappiness: 0
    security_opt:
      - label:disable
    stop_grace_period: 30s
    user: root
    userns_mode: keep-id:uid=0,gid=0

  service:
    entrypoint: !reset null
    extends: job
    healthcheck:
      interval: 10s
      start_interval: 2s
      start_period: 10s
      timeout: 3s
    init: true
    restart: unless-stopped
    user: !reset null
...
