---
api: {}
certificatesResolvers:
  lets-encrypt:
    acme:
      dnsChallenge:
        provider: ${DNS_PROVIDER:?}
      email: ${CERTIFICATE_EMAIL:?}
      keyType: EC384
      storage: /certificates/acme.json
entrypoints:
  http:
    address: :80
    http:
      encodeQuerySemicolons: true
      redirections:
        entryPoint:
          permanent: true
          to: https
    http3: {}
    reusePort: true
  https:
    address: :443
    asDefault: true
    http:
      encodeQuerySemicolons: true
      middlewares:
       - security-headers@file
      tls:
        certResolver: lets-encrypt
    http3: {}
    reusePort: true
experimental:
 plugins:
   static-response:
     moduleName: github.com/tuxgal/traefik_inline_response
     version: v0.1.2
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
ping:
  manualRouting: true
providers:
  file:
    filename: /etc/traefik/dynamic.yml
  swarm: {}
...
